### ISSUE TITLE
Example @javascript scenario attempting to use Goutte Driver

### ISSUE THREAD

**Issue by swestcott** [Behat/MinkExtension-example#1]
Running this example with the latest behat (2.4.0) and mink (1.4.0beta3), the example javascript scenario attempts to use the Goutte driver instead of Selenium2 which causes it to fail.

Console output: https://gist.github.com/2732669

Not sure if this is a issue with Behat, Mink, MinkExtension, this example or something else so raising to start with.

**Comment by everzet** [comment]
Should be fixed now.
