### ISSUE TITLE
Followed all steps - Does not work

### ISSUE THREAD

**Issue by andrewmori** [Behat/MinkExtension-example#10]
bin/behat

  Scenario: Searching for a page that does NOT exist           # features/search.feature:12
    Given I am on "/wiki/Main_Page"                            # InheritedFeatureContext::visit()
PHP Warning:  DOMXPath::query(): Invalid expression in /var/www/MinkExtension-example/vendor/symfony/dom-crawler/Symfony/Component/DomCrawler/Crawler.php on line 83

3 scenarios (3 failed)
12 steps (2 passed, 7 skipped, 3 failed)
0m1.223s

**Comment by stof** [comment]
Symfony DomCrawler 2.3.14, 2.3.15 and 2.4.5 have a bug in the XPath filtering, which affects Mink 1.5 when using the BrowserKitDriver or the GoutteDriver.

There is 3 ways to solve it:
- use an older release of Symfony
- use the dev version of Symfony 2.3 where the bug has been fixed (the fix has not been propagated to the dev version of 2.4 or 2.5 yet)
- use the Mink 1.6 dev version, which is not affected by the bug
