### ISSUE TITLE
haven't checked the checkbox by id 

### ISSUE THREAD

**Issue by med004** [Behat/MinkExtension-example#13]
I have make a test with behat but i have problem of checked checkbox by id

this is my feature:

```gherkin
Feature: dossiertest

      @javascript
      Scenario: List 2 files in a directory
       
        Given I am on the homepage
        Then I should see "hello"
        When I go to "/ajoutermed"
        And I fill in "test_medbundle_med_section" with "med"
        And I wait 1 seconds
        And I fill in "test_medbundle_med_info" with "123456"
        When I select "test_medbundle_med_genre_1" 
        And I wait 1 seconds
        When I press on "ajout"
        And I wait 3 seconds
        Then I should see "Med ajouter"
```

```php
         /**
            * @When I select :arg1
            */
    public function iSelect($arg1)
    {
        $page = $this->getSession()->getPage();
        $radioButton = $page->find('named', ['checkbox', $arg1]);
        if ($radioButton) {
            $select = $radioButton->getAttribute('name');
            $option = $radioButton->getAttribute('value');
            $page->checkField($select, $option);
                       return;
                        }

        var_dump("Radio button with label {$arg1} not found"); 
        var_dump($radioButton);

    }
```

and in my twig i have checkbox with id 'test_medbundle_med_genre_1' , when i select radio with same id 

but i should this problem:

```
    When I select "test_medbundle_med_genre_1"            # test\MedBundle\Behat\Context\AjouterContext::iSelect()
      mouseMoveTo
      Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
      System info: host: 'med-PC', ip: 'X.X.X.X', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_121'
      Driver info: driver.version: RemoteWebDriver (WebDriver\Exception\UnknownCommand)
```

help me please for resolved this problem and thanks

**Comment by stof** [comment]
Are you using the new Firefox driver for Selenium 3 ? If yes, please use the dev version of the Mink Selenium2Driver, which improved support for it (the Firefox driver is implementing the new W3C WebDriver spec, not the Selenium WebDriver spec, so there are a few places where things are not the same)

**Comment by stof** [comment]
if you don't want to use a dev version, there are 2 solutions available to you:
- use Selenium 2 instead of Selenium 3
- use Chrome/Chromium instead of Firefox

And if you stick to Firefox with Selenium 3, be aware that even in our dev version, the testsuite is not green with them (last time I tried), because the new Firefox driver was not yet feature-complete.

**Comment by med004** [comment]
I use selenium 3.3 and i use geckodriver v 0.14 and in other project i use selenium 2.4, for firefox i use last version ,maybe 52 but i have make update for browser firefox

**Comment by med004** [comment]
help me please
