### ISSUE TITLE
scenario 3 failed

### ISSUE THREAD

**Issue by gzmask** [Behat/MinkExtension-example#6]
I got:
When I fill in "search" with "Behavior Driv"  
       Form field with id|name|label|value "search" not found.

**Comment by stof** [comment]
Well, this is the issue with a demo depending on an external website. Wikipedia rename the search field.

**Comment by gzmask** [comment]
I've checked http://en.wikipedia.org and their search field is:

``` html
<input type="text" name="search" value="" title="Search Wikipedia [alt-shift-f]" accesskey="f" id="searchInput" tabindex="1" placeholder="Search" autocomplete="off">
```

I believe the name is still "search" here? 
Further more, if I removed the @javascript tag then the search step passed. 
Even if I add @javascript tag to scenario 2 and it will failed. 
I have also checked that selenium is running at port 4444.
So is this a selenium problem?
